name: Build and test the project

on:
  push:
    branches: [ master ]

jobs:
  name: Build contracts
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for Maven Wrapper
      run: chmod +x mvnw

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install contracts for Post generator
      run: ./mvnw clean package install --projects external-post-generator-contract

    - name: Install contracts for Comment generator
      run: ./mvnw clean package install --projects external-comment-generator-contract

    - name: Upload contracts
      uses: actions/upload-artifact@v2
      with:
        name: contracts
        path: /home/runner/.m2/repository/com/epam/community/z/*-contract/

    - name: Remove installed contracts in order not to cache them
      run: rm -rf /home/runner/.m2/repository/com/epam

  release:
    name: Release artifacts
    needs: build-contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Configure git
        run: |
          git config --global commiter.email "robot@github.com"
          git config --global commiter.name "GitHub Robot"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Restore contracts
        uses: actions/download-artifact@v2
        with:
          name: contracts
          path: /home/runner/.m2/repository/com/epam/community/z/

      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode release:prepare -Darguments="-DskipTests" -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN

      - name: Perform release
        run: mvn --batch-mode release:perform